// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact.proto

package go_micro_srv_contact

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Category             string   `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type CreateResponse struct {
	ErrMsg               string   `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ViewRequest struct {
	ContactID            string   `protobuf:"bytes,1,opt,name=contactID,proto3" json:"contactID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewRequest) Reset()         { *m = ViewRequest{} }
func (m *ViewRequest) String() string { return proto.CompactTextString(m) }
func (*ViewRequest) ProtoMessage()    {}
func (*ViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{2}
}

func (m *ViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewRequest.Unmarshal(m, b)
}
func (m *ViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewRequest.Marshal(b, m, deterministic)
}
func (m *ViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewRequest.Merge(m, src)
}
func (m *ViewRequest) XXX_Size() int {
	return xxx_messageInfo_ViewRequest.Size(m)
}
func (m *ViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewRequest proto.InternalMessageInfo

func (m *ViewRequest) GetContactID() string {
	if m != nil {
		return m.ContactID
	}
	return ""
}

type ViewResponse struct {
	Contact              *Contact `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewResponse) Reset()         { *m = ViewResponse{} }
func (m *ViewResponse) String() string { return proto.CompactTextString(m) }
func (*ViewResponse) ProtoMessage()    {}
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{3}
}

func (m *ViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewResponse.Unmarshal(m, b)
}
func (m *ViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewResponse.Marshal(b, m, deterministic)
}
func (m *ViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewResponse.Merge(m, src)
}
func (m *ViewResponse) XXX_Size() int {
	return xxx_messageInfo_ViewResponse.Size(m)
}
func (m *ViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewResponse proto.InternalMessageInfo

func (m *ViewResponse) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ListResponse struct {
	Contacts             []*Contact `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	ErrMsg               string     `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{5}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *ListResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type Contact struct {
	ContactID            string   `protobuf:"bytes,1,opt,name=contactID,proto3" json:"contactID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Category             string   `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	ErrMsg               string   `protobuf:"bytes,6,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{6}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetContactID() string {
	if m != nil {
		return m.ContactID
	}
	return ""
}

func (m *Contact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Contact) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Contact) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Contact) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Contact) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.contact.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.contact.CreateResponse")
	proto.RegisterType((*ViewRequest)(nil), "go.micro.srv.contact.ViewRequest")
	proto.RegisterType((*ViewResponse)(nil), "go.micro.srv.contact.ViewResponse")
	proto.RegisterType((*Empty)(nil), "go.micro.srv.contact.Empty")
	proto.RegisterType((*ListResponse)(nil), "go.micro.srv.contact.ListResponse")
	proto.RegisterType((*Contact)(nil), "go.micro.srv.contact.Contact")
}

func init() { proto.RegisterFile("contact.proto", fileDescriptor_a5036fff2565fb15) }

var fileDescriptor_a5036fff2565fb15 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x36, 0x4d, 0xda, 0x69, 0xeb, 0x61, 0x28, 0xb2, 0x54, 0x85, 0xba, 0x7a, 0x28,
	0x08, 0x39, 0xd4, 0x83, 0x78, 0x94, 0x2a, 0x52, 0xb0, 0x08, 0x05, 0xbd, 0xaf, 0x71, 0x08, 0x01,
	0xd3, 0xad, 0xbb, 0xab, 0xd2, 0xa3, 0x0f, 0xe6, 0xbb, 0x49, 0x37, 0x9b, 0x18, 0xa1, 0xad, 0x27,
	0x4f, 0xc9, 0xcc, 0x7c, 0x4c, 0xfe, 0x99, 0x7f, 0x02, 0xbd, 0x58, 0x2e, 0x8c, 0x88, 0x4d, 0xb4,
	0x54, 0xd2, 0x48, 0xec, 0x27, 0x32, 0xca, 0xd2, 0x58, 0xc9, 0x48, 0xab, 0xf7, 0xc8, 0xd5, 0xb8,
	0x84, 0xde, 0x44, 0x91, 0x30, 0x34, 0xa7, 0xd7, 0x37, 0xd2, 0x06, 0x11, 0xfc, 0x85, 0xc8, 0x88,
	0xd5, 0x87, 0xde, 0xa8, 0x3d, 0xb7, 0xef, 0xd8, 0x87, 0x26, 0x65, 0x22, 0x7d, 0x61, 0x0d, 0x9b,
	0xcc, 0x03, 0x64, 0x10, 0x66, 0xa4, 0xb5, 0x48, 0x88, 0xf9, 0x36, 0x5f, 0x84, 0x38, 0x80, 0x56,
	0x2c, 0x0c, 0x25, 0x52, 0xad, 0x58, 0xd3, 0x96, 0xca, 0x98, 0x8f, 0x60, 0xaf, 0xf8, 0xa0, 0x5e,
	0xca, 0x85, 0x26, 0xdc, 0x87, 0x80, 0x94, 0x9a, 0xe9, 0x84, 0x79, 0x96, 0x75, 0x11, 0x3f, 0x83,
	0xce, 0x63, 0x4a, 0x1f, 0x85, 0xb0, 0x43, 0x68, 0x3b, 0xd1, 0xd3, 0x6b, 0x47, 0xfe, 0x24, 0xf8,
	0x2d, 0x74, 0x73, 0xd8, 0x35, 0xbd, 0x80, 0xd0, 0x15, 0x2d, 0xdb, 0x19, 0x1f, 0x45, 0x9b, 0xe6,
	0x8f, 0x26, 0xf9, 0x73, 0x5e, 0xd0, 0x3c, 0x84, 0xe6, 0x4d, 0xb6, 0x34, 0x2b, 0x2e, 0xa0, 0x7b,
	0x97, 0x6a, 0x53, 0x76, 0xbc, 0x84, 0x96, 0x63, 0x34, 0xf3, 0x86, 0x8d, 0xbf, 0x5b, 0x96, 0x78,
	0x65, 0xc2, 0xfa, 0xaf, 0x09, 0xbf, 0x3c, 0x08, 0x1d, 0xbd, 0x7b, 0xbc, 0xff, 0x76, 0xa5, 0xa2,
	0x30, 0xa8, 0x2a, 0xb4, 0xaa, 0xac, 0x5b, 0xcf, 0x57, 0x86, 0x85, 0x4e, 0x55, 0x91, 0x18, 0x7f,
	0xd6, 0xa1, 0xeb, 0xf4, 0xcf, 0xd6, 0x6b, 0xc0, 0x07, 0x08, 0x72, 0x73, 0xf1, 0x64, 0xcb, 0x6e,
	0xaa, 0xb7, 0x36, 0x38, 0xdd, 0x0d, 0xe5, 0x8b, 0xe7, 0x35, 0xbc, 0x07, 0x7f, 0x6d, 0x2e, 0x1e,
	0x6f, 0xe6, 0x2b, 0x57, 0x32, 0xe0, 0xbb, 0x90, 0xb2, 0xe1, 0x14, 0xfc, 0xb5, 0xb7, 0x78, 0xb0,
	0x99, 0xb6, 0x07, 0xb0, 0xad, 0x55, 0xf5, 0x28, 0x78, 0xed, 0x29, 0xb0, 0x7f, 0xd7, 0xf9, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x32, 0x25, 0xf1, 0x6e, 0x03, 0x00, 0x00,
}
